### PR TITLE
Upgrade MetaMask SDK to 1.3.1

### PR DESCRIPTION
**Pull request by ecp4224**
This PR upgrades the MetaMask SDK to the latest version 1.3.1, which fixes several bugs and adds some new features:

## Bug Fixes

* Send `TERMINATE` message when `EndSession()` is used
* Enforce websockets to never use HTTP Pooling
* Handle case where decryption fails by restarting key exchange with wallet
* Several bug fixes with iOS and IL2CPP targets
* Fix bug where large chain id values caused exception
* Remove duplicated Starscream iOS dependency 

## Features

* Batch RPC Support (with type safety)
* Move Entirety of `MetaMask/Runtime` into single `dll` for both .NET Standard 2.0 and .NET Standard 2.1
* Added `ConnectAndSign()` function

### CODE REVIEW

**Comment by 0xFirekeeper** [comment]
Thanks @ecp4224 testing this cross platform now.

Can you set UnityUI ScriptableObject back to Spawn Canvas being off - currently MM canvas being spawned behind WalletProvider_MetaMask prefab - thanks

**Comment by 0xFirekeeper** [comment]
Unable to build for Windows, guessing the new editor script / assembly change made to ThirdwebCore causing issues `Assets\Thirdweb\Core\Plugins\MetaMask\Plugins\Libraries\evm.net\Editor\ContractGeneratorEditor.cs(16,6): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)`

Would remove that editor script or move it to higher up editor folder where Thirdweb.Editor.MetaMask asmdef lives

**Comment by ecp4224** [comment]
> Can you set UnityUI ScriptableObject back to Spawn Canvas being off - currently MM canvas being spawned behind WalletProvider_MetaMask prefab - thanks

Done 👍 

> Unable to build for Windows, guessing the new editor script / assembly change made to ThirdwebCore causing issues Assets\Thirdweb\Core\Plugins\MetaMask\Plugins\Libraries\evm.net\Editor\ContractGeneratorEditor.cs(16,6): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)

I moved it to `MetaMask.Editor`, so that should resolve that issue 👍

**Comment by 0xFirekeeper** [comment]
Able to build successfully on standalone and mobile, any notable/functional changes I should be aware of that you'd like to communicate before shipping this? @ecp4224

**Comment by ecp4224** [comment]
The only notable thing to mention is that the WebGL build now uses the MetaMask JS SDK, however after reviewing the changes here, I remembered that we have the JS SDK bundled into our own WebGL Template (not included here).

Wondering how this should be bundled into the Thirdweb WebGL Template? I can grab it dynamically or I can just add the following script tag

```
<script src="https://c0f4f41c-2f55-4863-921b-sdk-docs.github.io/cdn/metamask-sdk-unity.js"></script>
```

I can also simply disable the JS SDK Provider in `MetaMaskUnity` for now, so all platforms use the same logic inside Thirdweb SDK

**Comment by 0xFirekeeper** [comment]
Other than the added extra GUID in our asmdef this is good to go, let me know if it points to anything on your end, points to nothing on my end. Thanks.

**Comment by ecp4224** [comment]
I've commented out the [JS SDK Provider](https://github.com/thirdweb-dev/unity-sdk/pull/153/commits/8521b80e999cbc86489b7d6349eea182a26b08b5) for now and all build platforms will use the same provider logic. Perhaps in the future we can revisit this to use MetaMask JS SDK inside the typescript sdk bridge 😄 

I've also removed the unused GUID, unsure why Unity / Rider added this.

**Comment by 0xFirekeeper** [comment]
Happy to get it done on the typescript side later on.

LGTM, thanks Eddie.

**Pull request merged**
