### PR TITLE
Update MetaMask SDK to 1.2.2

### PR DESCRIPTION
**Pull request by ecp4224**
This PR updates the MetaMask SDK files located in `Assets/Thirdweb/Plugins/MetaMask` to match the latest version on the Unity Asset Store (1.2.2). This fixes several bugs, including but not limited to session resuming. Session resuming now works out-of-the box. 

This PR also updates the `MetaMaskProvider_Metamask` prefab and the `MetaMaskUI` script to instruct the user how to resume the session when the session was used less than an hour ago (no OTP is required in this case).

### CODE REVIEW

**Comment by 0xFirekeeper** [comment]
Hey, thanks for this. 
Are you able to connect from `Scene_Prefabs`?
With this version I'm stuck on `Connecting to MetaMask` popup on both an iPhone and Android.
Also, the `UnityUI` scriptable object should have Spawn Canvas off considering `WalletProvider_Metamask` exists here.
Finally, it would be good to fix all the warnings.
Thanks again.

**Comment by ecp4224** [comment]
I've tested on both Desktop (Windows) and Android and both seem to be working with session resuming. I will be able to test on an iOS device later today, but I suspect that it will also work, unless there is a build error.

## Desktop Demo

https://github.com/thirdweb-dev/unity-sdk/assets/879484/1265dd29-41d9-4a86-8128-3d2084a57975

## Android Demo

https://github.com/thirdweb-dev/unity-sdk/assets/879484/a85b0358-8fb8-497f-a6fb-a9d8a82a4997

**Comment by 0xFirekeeper** [comment]
Thanks for the info, will debug my issues and see if I can figure out why it doesn't work for me. In the meantime could you provide the MM mobile app version you are using (going to assume latest), and when you get to it, your XCode version/build flow so I can document best practices for users. Appreciate it.

**Comment by 0xFirekeeper** [comment]
I notice your QR code missing script warnings when connecting, those mean you didn't turn off Spawn Canvas in MetaMask's UnityUI ScriptableObject, could it be overriding some settings from the main WalletProvider_MetaMask UI causing these issues?

Either way stuck on Connecting to MetaMask with your same Editor + Android phone setup.

Screenshot_2024-01-10-17-23-57-82_3ce871bb60cb313382b75690e63e41d0

**Comment by ecp4224** [comment]
I've updated the PR to remove all warnings and to fix the MetaMask config not being set before it's initialized (perhaps a better API is needed in MetaMask SDK to make this easier)

I'm using the latest version of MetaMask mobile to test

**Comment by 0xFirekeeper** [comment]
Appreciate it, unfortunately it still won't connect for me but I think you changed all that is needed. Wonder what typically causes connection to hang, invalid metadata in this case perhaps? Tried clearing cache/session data, reinstalling the app etc. Same behavior on iOS and Android when I try to scan QR from Windows editor, hangs.

**Comment by 0xFirekeeper** [comment]
Was able to get past it using a combination of https://1.1.1.1/ and clearing connections
Also tested on Android
If all goes well on iOS will merge this

**Comment by 0xFirekeeper** [comment]
Using XCode 15.1 and Unity 2022.3.15f1 I'm able to build. Previous versions of Unity 2022 may run into issues with XCode when running the GameAssemly script automatically during the build process in XCode.

However, the app crashes on startup. Even after reimporting the MM iOS folder on a Mac and clean building.

Logs:
```
2024-01-11 02:50:19.135331+0300 UnitySDK[12577:4171737] [general] Error loading /var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/UnityFramework.framework/UnityFramework (135): dlopen(/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/MetaMask_iOS.framework/MetaMask_iOS
 Referenced from: <149F5E2E-4F9D-3798-8346-1194A21E0D10> /private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/UnityFramework.framework/UnityFramework
 Reason: tried: '/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/MetaMask_iOS.framework/MetaMask_iOS' (no such file)
2024-01-11 02:50:19.156427+0300 UnitySDK[12577:4171737] [general] Error loading /var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/UnityFramework.framework/UnityFramework (135): dlopen(/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/MetaMask_iOS.framework/MetaMask_iOS
 Referenced from: <149F5E2E-4F9D-3798-8346-1194A21E0D10> /private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/UnityFramework.framework/UnityFramework
 Reason: tried: '/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/MetaMask_iOS.framework/MetaMask_iOS' (no such file), '/private/var/containers/Bundle/Application/8C945DC9-4DF7-4CB9-9B20-9A35424526D6/UnitySDK.app/Frameworks/MetaMask_iOS.framework/MetaMask_iOS' (no such file)
```

**Comment by ecp4224** [comment]
> However, the app crashes on startup. Even after reimporting the MM iOS folder on a Mac and clean building.
We were able to reproduce this as well, a "workaround" we found was doing this

> If building for iOS and missing a Metamask package, you can double click on main.unitypackage under Assets\Thirdweb\Plugins\MetaMask\Installer\Packages and reimport the iOS folder

However I will push a proper fix for this issue, I believe some `meta` files got overwritten

**Comment by 0xFirekeeper** [comment]
Hm yes that was the solution I wrote for cases where iOS specific files are not persisted or committed properly as .meta from other platforms, though in this case it didn't seem to solve the issue. Let me know if you figure out another workaround.

**Comment by ecp4224** [comment]
@0xFirekeeper can you try the latest changes to this PR? Internally we confirmed it works on iOS 13 and 17. The timestamp for the iOS fix was older so it may show up earlier in the commit list.

**Comment by 0xFirekeeper** [comment]
No luck so far, will try messing with iOS versions more..

**Comment by 0xFirekeeper** [comment]
Crashes on iOS 13 and 16, reimporting mm package iOS folder does not help either. Any other settings that might be relevant if you got it to work? A video of the build and running processes might be useful. @ecp4224

**Comment by 0xFirekeeper** [comment]
ty

**Comment by coding-velociraptor** [comment]
@ecp4224 @ezgi-cengiz thank you for the update! We are able to build and test the app locally. However, we receive validation errors when uploading to App Store Connect:

- Asset validation failed (90205) Invalid Bundle. The bundle at 'xxx.app/Frameworks/MetaMask_iOS.framework/Frameworks/Pods_MetaMask_iOS.framework' contains disallowed nested bundles
- Asset validation failed Invalid Bundle. The bundle at 'xxx.app/Frameworks/MetaMask_iOS.framework' contains disallowed file 'Frameworks'. (ID: d34a1665-25c5-4d55-b0e8-3edb664aea8d) 
- Asset validation failed CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.cocoapods.Starscream' under the iOS application 'xxx. (ID: 6e27a6bc-55c3-4a05-822f-4fb240e60c2b)

Do you have pointers?

**Comment by coding-velociraptor** [comment]
> @ecp4224 @ezgi-cengiz thank you for the update! We are able to build and test the app locally. However, we receive validation errors when uploading to App Store Connect:
> 
>     * Asset validation failed (90205) Invalid Bundle. The bundle at 'xxx.app/Frameworks/MetaMask_iOS.framework/Frameworks/Pods_MetaMask_iOS.framework' contains disallowed nested bundles
> 
>     * Asset validation failed Invalid Bundle. The bundle at 'xxx.app/Frameworks/MetaMask_iOS.framework' contains disallowed file 'Frameworks'. (ID: d34a1665-25c5-4d55-b0e8-3edb664aea8d)
> 
>     * Asset validation failed CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.cocoapods.Starscream' under the iOS application 'xxx. (ID: 6e27a6bc-55c3-4a05-822f-4fb240e60c2b)
> 
> 
> Do you have any pointers?

We found the following workaround:
```sh 
rm -rf Thirdweb/Plugins/MetaMask/Plugins/iOS/iphoneos/MetaMask_iOS.framework/Frameworks
```

Are those nested frameworks correct?

**Pull request merged**
